name: Slither Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  slither:
    name: Slither Static Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npm run compile

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Slither
        run: |
          pip3 install slither-analyzer
          pip3 install solc-select
          solc-select install 0.8.20
          solc-select use 0.8.20

      - name: Verify compilation
        run: |
          echo "Checking artifacts directory..."
          ls -la artifacts/contracts/ || echo "Artifacts not found"

      - name: Run Slither
        id: slither
        run: |
          echo "Running Slither analysis..."
          npm run slither:sarif 2>&1 | tee slither-output.log || echo "Slither analysis encountered issues"

          echo "Checking for SARIF file..."
          if [ -f slither-results.sarif ]; then
            echo "SARIF file generated successfully"
            echo "File size: $(wc -c < slither-results.sarif) bytes"
            echo "sarif_exists=true" >> $GITHUB_OUTPUT
          else
            echo "SARIF file not generated"
            echo "Listing current directory:"
            ls -la
            echo "sarif_exists=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Upload Slither logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: slither-logs
          path: slither-output.log
          retention-days: 7

      - name: Upload Slither SARIF results
        uses: github/codeql-action/upload-sarif@v3
        if: steps.slither.outputs.sarif_exists == 'true'
        with:
          sarif_file: slither-results.sarif
          category: slither

      - name: Upload Slither results as artifact
        uses: actions/upload-artifact@v4
        if: steps.slither.outputs.sarif_exists == 'true'
        with:
          name: slither-results
          path: slither-results.sarif
          retention-days: 30

      - name: Generate JSON report
        if: always()
        run: npm run slither:json || true

      - name: Upload JSON report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: slither-json-report
          path: slither-results.json
          retention-days: 30
